### ISSUE TITLE
Bolts to hold feet to shells vibrates loose

### ISSUE THREAD

**Issue by eldrinos** [eldrinos/m3-d1c#11]
As the name suggests, it looks like we need to go about and add some LockTite to the bolts holding the foot shells together.

**Comment by Crispypags** [comment]
4 of 6 nuts replaced with vinyl lock nuts and righted 2 nuts still need to be tightened

**Comment by Crispypags** [comment]
remaining 2 lock nuts attached and secured that foot shouldt be going anywhere

**Comment by Crispypags** [comment]
Reopening with new issue this time the foot hose nuts vibrated off …. Well one of them did… gonna just swap these out with lock nuts just to be safe… if i can find them this big
