### ISSUE TITLE
Dome bump bolt fell off

### ISSUE THREAD

**Issue by eldrinos** [eldrinos/m3-d1c#12]
**As title.** LockTite should do the trick.

**Comment by Crispypags** [comment]
Must locate dome bump probably in back pack was not in kilt pockets

**Comment by Crispypags** [comment]
> **As title.** LockTite should do the trick.

Got a vinyl lock nut if it gives us issue going on will fall back and get a regular nut and lock tight

**Comment by eldrinos** [comment]
Vinyl lock nut installed, however not enough time/torque to get it really trued up. that being said it's not gonna move for a while, so mission accomplished - leaving this issue open for now in case we need to make changes.

**Comment by Crispypags** [comment]
this should be good if we need to reopen will do at later date
