### ISSUE TITLE
Repair “chrome” strut 

### ISSUE THREAD

**Issue by Crispypags** [eldrinos/m3-d1c#17]
Repair the 3D printed strut on medics left leg probably just needs hot glue will upgrade at later time

**Comment by eldrinos** [comment]
I believe Chris has glued the strut back on, but the head of the part is still missing. Since it's about coin sized, maybe a magnet or a spray painted fake quarter would do the trick?

**Comment by Crispypags** [comment]
Correct head is still missing I'll look for a washer at Home Depot tonight
